# -*- coding: utf-8 -*-
"""live_organisme

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4DNQhBALcOIqQ98e23ku56Z2GKn9pSF
"""

def classify_entity():
    print("--- Biological Entity Classification System ---")
    print("Please answer 'yes' or 'no' to the following scientific criteria:\n")

    # List of scientific criteria for life
    criteria = [
         ("Organization", "Composed of one or more cells, the fundamental units of life?"),
        ("Metabolism", "Transforming nutrients into energy and disposing of waste products?"),
        ("Growth and Development", " Increasing in mass and changing over time through cellular processes?"),
        ("Responsiveness", "Reacting to internal or external environmental changes (like light or temperature)?"),
        ("Reproduction", "Producing new individual organisms to ensure species survival?"),
        ("Homeostasis" , " Regulating the internal environment to maintain stable, life-supporting conditions?"),
        ("Adaptation" , "Evolving over generations to suit the surrounding environment?")
    ]

    is_living = True

    for term, question in criteria:
        user_input = input(f"{term}: {question} (yes/no): ").strip().lower()

        # Validate input and check condition
        if user_input == 'no':
            is_living = False
            # We continue asking or break based on the logic:
            # In biology, an entity must meet ALL criteria to be considered fully "living".
            break
        elif user_input != 'yes':
            print("Invalid input. Please restart and type 'yes' or 'no'.")
            return

    print("\n-------------------------------------------")
    if is_living:
        print("RESULT: The entity is classified as a LIVING ORGANISM.")
        print("Reason: It satisfies all fundamental biological requirements for life.")
    else:
        print("RESULT: The entity is classified as NON-LIVING.")
        print("Reason: To be considered living, an entity must satisfy all biological criteria simultaneously.")
    print("-------------------------------------------")

if __name__ == "__main__":
    classify_entity()